### PR TITLE
Fix Print::printf implementation

### LINKED ISSUE #62: Print::printf implementation issue
current `Print::printf` implementation does not call the `write` virtual function, which make it always print to Serial.

ref implementation  that use `write`:

https://github.com/esp8266/Arduino/blob/bb79e9076e8402c81c24efbabd19f1baab1c6bd1/cores/esp8266/Print.cpp#L50-L71

### PR DESCRIPTION
**Pull request by tsl0922**
Requirement: https://github.com/h2zero/platform-n-able/pull/3.

Fixes #62.

### CODE REVIEW

**Comment by h2zero** [comment]
Thanks! Only concern I have is that it will likely cause a stack overflow for constrained devices, nRF51 and nRF52810 etc.. I will test it and see.

**Comment by tsl0922** [comment]
https://github.com/esp8266/Arduino/blob/bb79e9076e8402c81c24efbabd19f1baab1c6bd1/cores/esp8266/Print.cpp#L50-L71

The code above maybe better, it uses a smaller buffer first, alloc if the buffer overflow.

**Comment by tsl0922** [comment]
Follow up to https://github.com/h2zero/n-able-Arduino/pull/68#issuecomment-2591505582

I have a worked implementation now, if you are OK with the changes, I can open another PR to this one @h2zero 

```
--- a/builder/frameworks/arduino/nrf5.py
+++ b/builder/frameworks/arduino/nrf5.py
@@ -71,6 +71,8 @@ env.Append(

     CPPPATH=[
         join(FRAMEWORK_DIR, "cores", board.get("build.core")),
+        join(FRAMEWORK_DIR, "cores", board.get("build.core"),
+            "libc", "printf"),
         join(FRAMEWORK_DIR, "cores", board.get("build.core"),
              "nordic", "nrfx"),
         join(FRAMEWORK_DIR, "cores", board.get("build.core"),
```

```
--- a/cores/nRF5/Print.cpp
+++ b/cores/nRF5/Print.cpp
@@ -22,6 +22,7 @@
 #include <string.h>
 #include <math.h>
 #include "Arduino.h"
+#include "printf.h"

 #include "Print.h"

@@ -187,11 +188,16 @@ size_t Print::println(const Printable& x)
   return n;
 }

+extern "C" void streamOutput(char character, void* arg)
+{
+  (static_cast<Print *>(arg))->write(character);
+}
+
 int Print::printf(const char* format, ...)
 {
   va_list va;
   va_start(va, format);
-  int ret = vprintf(format, va);
+  int ret = vfctprintf(&streamOutput, this, format, va);
   va_end(va);
   return ret;
 }
```

**Comment by h2zero** [comment]
@tsl0922 That is probably the better solution, please open PR's for this.

**Comment by tsl0922** [comment]
> @tsl0922 That is probably the better solution, please open PR's for this.

Done. This PR has been updated, PR for platform: https://github.com/h2zero/platform-n-able/pull/3.

File: cores/nRF5/Print.cpp [hunk 1]
```diff
@@ -22,6 +22,7 @@
 #include <string.h>
 #include <math.h>
 #include "Arduino.h"
+#include "printf.h"
```
Comment (h2zero) [inline cores/nRF5/Print.cpp:25]: Let's just change this to `#include "libc/printf/printf.h"` and then we don't need to platform update and will also fix Arduino builds.

File: cores/nRF5/Print.cpp [hunk 2]
```diff
@@ -187,11 +188,16 @@ size_t Print::println(const Printable& x)
   return n;
 }
 
+extern "C" void streamOutput(char character, void* arg)
+{
+  (static_cast<Print *>(arg))->write(character);
+}
+
```
Comment (h2zero) [inline cores/nRF5/Print.cpp:195]: Can we move this outside the class definition?

**Review by h2zero — CHANGES_REQUESTED** [review]
Looks good, just need to fix a couple things.

File: cores/nRF5/Print.cpp (hunk 2 above)
Comment (tsl0922) [reply cores/nRF5/Print.cpp:195]: Where?

Comment (tsl0922) [reply cores/nRF5/Print.cpp]: Moved it to the top of the file.
